Repository CodeExperts/DonnyMoney, pull requests merged in 2024-11, with the labels that each got.

#13 [BE] 기능구현(monthPayment,monthPlan, showQuizResult, showQuizResultTop3)
  server/pom.xml
  server/src/main/java/com/web/spring/DonnyMoneyApplication.java
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/dto/child/payment/PayRequestDto.java
  server/src/main/java/com/web/spring/dto/child/payment/PayResponseDto.java
  server/src/main/java/com/web/spring/entity/Child.java
  server/src/main/java/com/web/spring/entity/Payment.java
  server/src/main/java/com/web/spring/global/mapper/ChildMapper.java
  server/src/main/java/com/web/spring/repository/ChildRepository.java
  server/src/main/java/com/web/spring/service/ChildService.java
  server/src/main/resources/application.properties
Labels: feat

#15 [BE] feat : Edu Quiz 기능 구현
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/dto/child/quiz/QuizResponseDto.java
  server/src/main/java/com/web/spring/entity/Payment.java
  server/src/main/java/com/web/spring/repository/ChildRepository.java
  server/src/main/java/com/web/spring/service/ChildService.java
Labels: feat

#17 [FE] feat : 소비 계획 기능 구현 완료
  client/src/App.js
  client/src/Navirouter.js
  client/src/components/layouts/Header.js
  client/src/components/pages/MGMT/plan/PlanForm.js
  client/src/components/pages/MGMT/plan/SaveForm.js
  client/src/components/pages/MGMT/plan/UpdateForm.js
  client/src/pages/HomePage.js
  client/src/pages/PlanPage.js
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/controller/ParentController.java
  server/src/main/java/com/web/spring/dto/child/payment/PayRequestDto.java
  server/src/main/java/com/web/spring/dto/child/plan/PlanRequestDto.java
  server/src/main/java/com/web/spring/dto/child/point/PointRequestDto.java
  server/src/main/java/com/web/spring/dto/parent/ParentReportResponseDto.java
  server/src/main/java/com/web/spring/global/mapper/ChildMapper.java
  server/src/main/java/com/web/spring/repository/ChildRepository.java
  server/src/main/java/com/web/spring/service/ChildService.java
  server/src/main/java/com/web/spring/service/ParentService.java
Labels: feat

#21 [BE] fix : Wish 일부 기능 return 값 변경 #14
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/service/ChildService.java
Labels: fix

#31 [BE] fix : childService 기능 구현 버그 픽스
  server/src/main/java/com/web/spring/DonnyMoneyApplication.java
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/config/WebMvcConfig.java
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/controller/ParentController.java
  server/src/main/java/com/web/spring/dto/SignInResponseDto.java
  server/src/main/java/com/web/spring/dto/child/ChildRequestDto.java
  server/src/main/java/com/web/spring/dto/child/wish/WishRequestDto.java
  server/src/main/java/com/web/spring/dto/child/wish/WishResponseDto.java
  server/src/main/java/com/web/spring/dto/parent/ParentResponeseDto.java
  server/src/main/java/com/web/spring/entity/Child.java
  server/src/main/java/com/web/spring/entity/IsFinish.java
  server/src/main/java/com/web/spring/entity/Member.java
  server/src/main/java/com/web/spring/entity/Parent.java
  server/src/main/java/com/web/spring/entity/Quiz.java
  server/src/main/java/com/web/spring/entity/Wish.java
  server/src/main/java/com/web/spring/global/BooleanToYNConverter.java
  server/src/main/java/com/web/spring/jwt/JWTFilter.java
  server/src/main/java/com/web/spring/jwt/JWTUtil.java
  server/src/main/java/com/web/spring/jwt/LoginFilter.java
  server/src/main/java/com/web/spring/jwt/RefreshToken.java
  server/src/main/java/com/web/spring/jwt/RefreshTokenRepository.java
  server/src/main/java/com/web/spring/repository/ChildRepository.java
  server/src/main/java/com/web/spring/repository/ParentRepository.java
  server/src/main/java/com/web/spring/repository/WishRepository.java
  server/src/main/java/com/web/spring/security/CustomMemberDetails.java
  server/src/main/java/com/web/spring/security/CustomMemberDetailsService.java
  server/src/main/java/com/web/spring/service/ChildService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/web/spring/DonnyMoneyApplicationTests.java
  server/src/test/java/com/web/spring/test/WishRepositoryUnitTest.java
Labels: fix

#32 [BE]feat: BackEnd 1차완료
  server/src/main/java/com/web/spring/DonnyMoneyApplication.java
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/config/WebMvcConfig.java
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/controller/ParentController.java
  server/src/main/java/com/web/spring/dto/SignInResponseDto.java
  server/src/main/java/com/web/spring/dto/child/ChildRequestDto.java
  server/src/main/java/com/web/spring/dto/child/wish/WishRequestDto.java
  server/src/main/java/com/web/spring/dto/child/wish/WishResponseDto.java
  server/src/main/java/com/web/spring/dto/parent/ParentResponeseDto.java
  server/src/main/java/com/web/spring/entity/Child.java
  server/src/main/java/com/web/spring/entity/IsFinish.java
  server/src/main/java/com/web/spring/entity/Member.java
  server/src/main/java/com/web/spring/entity/Parent.java
  server/src/main/java/com/web/spring/entity/Quiz.java
  server/src/main/java/com/web/spring/entity/Wish.java
  server/src/main/java/com/web/spring/global/BooleanToYNConverter.java
  server/src/main/java/com/web/spring/jwt/JWTFilter.java
  server/src/main/java/com/web/spring/jwt/JWTUtil.java
  server/src/main/java/com/web/spring/jwt/LoginFilter.java
  server/src/main/java/com/web/spring/jwt/RefreshToken.java
  server/src/main/java/com/web/spring/jwt/RefreshTokenRepository.java
  server/src/main/java/com/web/spring/repository/ChildRepository.java
  server/src/main/java/com/web/spring/repository/ParentRepository.java
  server/src/main/java/com/web/spring/repository/WishRepository.java
  server/src/main/java/com/web/spring/security/CustomMemberDetails.java
  server/src/main/java/com/web/spring/security/CustomMemberDetailsService.java
  server/src/main/java/com/web/spring/service/ChildService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/web/spring/DonnyMoneyApplicationTests.java
  server/src/test/java/com/web/spring/test/WishRepositoryUnitTest.java
Labels: feat

#45 [FE]design: icons폴더 추가및 icon 추가
  client/package-lock.json
  client/package.json
  client/public/icons/balloons.png
  client/public/icons/cvs.png
  client/public/icons/food.png
  client/public/icons/loud speaker.png
  client/public/icons/others.png
  client/public/icons/saving.png
  client/public/icons/shopping.png
  client/public/icons/shoppingBag.png
  client/public/icons/star.png
  client/public/icons/transport.png
Labels: documentation, styled

#49 [FE] feat: 공통모달,버튼 추가
  client/src/App.jsx
  client/src/components/commons/Button.jsx
  client/src/components/commons/Modal.jsx
  client/src/components/layouts/Button.jsx
  client/src/pages/common/LandingPage.jsx
Labels: feat

#53 [BE] : JWT ChildController url 수정
  client/public/images/bell_1.png
  client/public/images/bell_2.png
  client/src/App.jsx
  client/src/Navirouter.js
  client/src/components/layouts/Header.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/pages/common/LoginPage.jsx
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/dto/child/FindMyParentDto.java
  server/src/main/java/com/web/spring/jwt/LoginFilter.java
  server/src/main/java/com/web/spring/repository/ParentRepository.java
  server/src/main/java/com/web/spring/service/ChildService.java
Labels: fix

#54 #37 [FE] feat : 로그인 기능 구현 완효
  client/.vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/styles/GlobalStyle.jsx
Labels: feat

#55 [BE] fix : security config, controller, dto 수정, [FE] feat : 회원가입 페이지 추가, 레이아웃 수정, 랜딩페이지 레이아웃 추가
  client/src/App.jsx
  client/src/Navirouter.js
  client/src/components/layouts/Header.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/child/register/ChildRegisterForm.jsx
  client/src/components/pages/landing/Landing1.jsx
  client/src/components/pages/landing/Landing2.jsx
  client/src/components/pages/landing/Landing3.jsx
  client/src/components/pages/landing/Landing4.jsx
  client/src/components/pages/parent/register/ParentRegisterForm.jsx
  client/src/index.js
  client/src/pages/common/LandingPage.jsx
  client/src/pages/common/RegisterPage.jsx
  client/src/styles/GlobalStyle.jsx
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/dto/child/FindMyParentDto.java
  server/src/main/java/com/web/spring/service/ChildService.java
Labels: feat

#56 [FE] feat : 부모페이지 아이,날짜 조회 navbar 추가
  client/public/icons/down.png
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/parent/SelectOptionNav.jsx
  client/src/pages/common/SelectUserType.jsx
  client/src/pages/parent/MonthlyReportPage.jsx
Labels: feat

#58 [FE] feat : 랜딩 3,4페이지 추가, fix : style 파일 정리
  client/public/icons/landing4-icon1.png
  client/public/icons/landing4-icon2.png
  client/public/icons/landing4-icon3.png
  client/src/App.jsx
  client/src/Navirouter.js
  client/src/components/layouts/Header.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/landing/Landing1.jsx
  client/src/components/pages/landing/Landing2.jsx
  client/src/components/pages/landing/Landing3.jsx
  client/src/components/pages/landing/Landing4.jsx
  client/src/components/pages/parent/SelectOptionNav.jsx
  client/src/index.css
  client/src/index.js
  client/src/pages/common/LandingPage.jsx
  client/src/pages/common/RegisterPage.jsx
  client/src/styles/GlobalStyle.jsx
Labels: fix, feat

#59 #35 [FE] feat : 랜딩 페이지 1, 2, 3, 4 기능 구현
  client/package-lock.json
  client/package.json
  client/public/images/coin-1.svg
  client/public/images/coin-2.svg
  client/public/images/coin-3.svg
  client/public/images/final_Donny.png
  client/public/images/stockCoin1.png
  client/public/images/stockCoin2.png
  client/public/images/text1.png
  client/public/images/text2.png
  client/public/images/text3.png
  client/public/images/worry.png
  client/src/Navirouter.js
  client/src/components/commons/Coin.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/components/pages/landing/Landing1.jsx
  client/src/components/pages/landing/Landing2.jsx
Labels: feat

#60 #10 #35 [FE,BE] fix : LocalStorage 내 role 저장
  client/src/components/pages/LoginForm.jsx
  server/src/main/java/com/web/spring/jwt/LoginFilter.java
Labels: fix

#61 [FE] feat : 얇은 폰트 추가 및 LocalStorage role 제거
  client/public/assets/fonts/Hakgyoansim Dunggeunmiso OTF R.otf
  client/public/assets/fonts/Hakgyoansim_Dunggeunmiso_TTF_R.ttf
  client/src/components/layouts/Header.jsx
  client/src/components/pages/landing/Landing1.jsx
  client/src/components/pages/landing/Landing3.jsx
  client/src/components/pages/landing/Landing4.jsx
  client/src/styles/GlobalStyle.jsx
  server/src/main/java/com/web/spring/config/WebMvcConfig.java
Labels: fix

#62 #38 [FE] feat : 이번 달 내가 쓴 돈 css 구현
  client/public/images/text1.png
  client/public/images/text2.png
  client/public/images/text3.png
  client/src/components/pages/child/payment/PaymentReport.jsx
  client/src/components/pages/parent/Agreement.jsx
  client/src/pages/parent/AgreementPage.jsx
Labels: feat

#67 #38 [FE] styled : 내가 쓴 돈 css 수정
  client/public/images/contract.jpg
  client/public/images/stamp.png
  client/src/components/pages/child/payment/PaymentReport.jsx
  client/src/components/pages/parent/agreement/Agreement.jsx
  client/src/components/pages/parent/agreement/Order.jsx
  client/src/pages/parent/AgreementPage.jsx
Labels: styled

#68 [FE] feat : 부모, 아이 별 헤더 Navigation 수정
  client/src/components/layouts/Header.jsx
Labels: fix, feat

#70 [FE] feat : 헤더 로그아웃 버튼 수정, 알림목록 추가, AuthContext 유저정보 분리 [BE] fix : Notification 엔터티 읽음여부 추가
  .DS_Store
  .gitignore
  client/public/images/sample-dad.png
  client/public/images/sample-sister.png
  client/src/App.jsx
  client/src/Navirouter.js
  client/src/components/commons/ModalNotify.jsx
  client/src/components/layouts/Header.jsx
  client/src/components/layouts/Layout.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/components/pages/child/ChildNotificationIcon.jsx
  client/src/components/pages/child/register/ChildRegisterForm.jsx
  client/src/components/pages/parent/ParentNotificationIcon.jsx
  client/src/components/pages/parent/register/ParentRegisterForm.jsx
  client/src/context/AuthContext.js
  client/src/pages/child/ChildReportPage.jsx
  client/src/pages/child/EduPage.jsx
  client/src/pages/child/MyWishListPage.jsx
  client/src/pages/common/RegisterPage.jsx
  client/src/pages/parent/AgreementPage.jsx
  client/src/pages/parent/WishListPage.jsx
  client/src/pages/test/child/SendTest.jsx
  client/src/pages/test/parent/ParentTest.jsx
  client/src/services/NotificationService.js
  client/src/services/sseEmitter.js
  server/.gitignore
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/controller/NotificationController.java
  server/src/main/java/com/web/spring/dto/notification/NotificationRequestDto.java
  server/src/main/java/com/web/spring/dto/notification/NotificationResponseDto.java
  server/src/main/java/com/web/spring/entity/Notification.java
  server/src/main/java/com/web/spring/repository/NotificationRepository.java
  server/src/main/java/com/web/spring/service/NotificationService.java
Labels: fix, feat

#69 [FE]소비계획 페이지 #36
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Navirouter.js
  client/src/components/layouts/Header.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/components/pages/child/plan/DoughnutChart.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/components/pages/child/plan/SaveForm.jsx
  client/src/components/pages/child/plan/SelectBox.jsx
  client/src/components/pages/child/plan/UpdateForm.jsx
  client/src/pages/child/MoneyPlanPage.jsx
  client/src/pages/context/MoneyPlanContext.js
  server/src/main/java/com/web/spring/controller/ChildController.java
  server/src/main/java/com/web/spring/service/ChildService.java
Labels: fix, feat, styled

#84 #65 [FE] fix : 결제 시, 아이에게 알림가도록 수정
  client/src/components/pages/parent/agreement/Agreement.jsx
Labels: fix

#87 # 86 [BE] feat : 카카오페이 결제기능 구현
  server/src/main/java/com/web/spring/KakaoPayment/Amount.java
  server/src/main/java/com/web/spring/KakaoPayment/ApproveResponseDto.java
  server/src/main/java/com/web/spring/KakaoPayment/KakaoPayController.java
  server/src/main/java/com/web/spring/KakaoPayment/KakaoPayService.java
  server/src/main/java/com/web/spring/KakaoPayment/OrdResponseDto.java
  server/src/main/java/com/web/spring/KakaoPayment/ReadyResponseDto.java
  server/src/main/java/com/web/spring/config/SecurityConfig.java
  server/src/main/java/com/web/spring/entity/PointOrder.java
Labels: feat

#88 [FE] feat: 위시 기능 추가중
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/commons/WishItemCard.jsx
  client/src/components/pages/child/payment/ReceiveMessage.jsx
  client/src/components/pages/child/plan/DoughnutChart.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/components/pages/child/plan/SelectBox.jsx
  client/src/components/pages/child/wish/Activewish.jsx
  client/src/components/pages/child/wish/WishDetailBox.jsx
  client/src/pages/child/MoneyPlanPage.jsx
  client/src/pages/child/MyWishListPage.jsx
  client/src/pages/parent/MonthlyReportPage.jsx
  server/src/main/java/com/web/spring/controller/NotificationController.java
Labels: feat

#89 [FE] fix : WishDetailBox.jsx 수정
  client/public/images/donnyFamily-prev.png
  client/public/images/donnyFamily.png
  client/src/components/commons/WishItemCard.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/components/pages/child/payment/ReceiveMessage.jsx
  client/src/components/pages/child/wish/Activewish.jsx
  client/src/components/pages/child/wish/WishDetailBox.jsx
  client/src/data/wishSlickDummyData.js
  client/src/pages/child/MoneyPlanPage.jsx
  client/src/pages/child/MyWishListPage.jsx
Labels: fix

#90 [FE] feat : MyWishListPage.jsx 성공한 위시리스트 추가
  client/public/icons/celebrate.png
  client/public/icons/celebrate2.png
  client/public/icons/celebrate3.png
  client/public/icons/celebrate5.png
  client/public/icons/celebrate6.png
  client/src/components/commons/WishItemCard.jsx
  client/src/components/pages/LoginForm.jsx
  client/src/components/pages/child/register/FinishWishList.jsx
  client/src/components/pages/parent/register/ParentRegisterForm.jsx
  client/src/data/wishFinishListDummyData.js
  client/src/pages/child/MyWishListPage.jsx
  client/src/pages/common/RegisterPage.jsx
  client/src/pages/parent/WishListPage.jsx
  server/src/main/java/com/web/spring/controller/NotificationController.java
Labels: feat

#92 [FE]feat: 동적 버튼 추가
  client/src/components/pages/child/plan/DoughnutChart.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  server/src/test/java/com/web/spring/test/ChildServiceCommandLineTest.java
Labels: feat

#94 [FE, BE] FE_이미지 수정 및 BE_배포 url 변경
  client/public/images/bell_2.png
  client/src/components/pages/child/payment/ReceiveMessage.jsx
  server/src/main/java/com/web/spring/KakaoPayment/KakaoPayController.java
  server/src/main/java/com/web/spring/KakaoPayment/KakaoPayService.java
  server/src/main/java/com/web/spring/advice/DefaultExceptionAdvice.java
Labels: fix

#95 [BE] Notification keep alive 수정 및 아이,부모 구독 엔드포인트변경, [FE] SSE emitter 메소드 수정
  client/src/components/pages/child/ChildNotificationIcon.jsx
  client/src/components/pages/landing/Landing1.jsx
  client/src/components/pages/parent/ParentNotificationIcon.jsx
  client/src/pages/child/MoneyPlanPage.jsx
  client/src/services/sseEmitter.js
  server/src/main/java/com/web/spring/controller/NotificationController.java
  server/src/main/java/com/web/spring/service/NotificationService.java
Labels: fix

#96 [FE] SendMessage.jsx 선택한 아이의 num으로 메세지전송 안되는 이슈 수정
  client/src/components/pages/parent/monthly-report/SendMessage.jsx
Labels: fix

#98 [FE]랜딩페이지 및 Plan,Wish Page수정
  client/public/icons/cancle.png
  client/public/images/PlanPageimg.png
  client/public/images/QuizPageimg.png
  client/public/images/WishPageimg.png
  client/src/components/pages/child/ChildNotificationIcon.jsx
  client/src/components/pages/child/edu/EduQuiz.jsx
  client/src/components/pages/child/edu/EduVideo.jsx
  client/src/components/pages/child/payment/PaymentReport.jsx
  client/src/components/pages/child/payment/ReceiveMessage.jsx
  client/src/components/pages/child/plan/DoughnutChart.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/components/pages/child/plan/SelectBox.jsx
  client/src/components/pages/child/register/ChildRegisterForm.jsx
  client/src/components/pages/child/wish/ActiveWish.jsx
  client/src/components/pages/child/wish/WishDetailBox.jsx
  client/src/components/pages/landing/Landing3.jsx
  client/src/components/pages/parent/ParentNotificationIcon.jsx
  client/src/components/pages/parent/SelectOptionNav.jsx
  client/src/components/pages/parent/monthly-report/SendMessage.jsx
  client/src/components/pages/parent/register/ParentRegisterForm.jsx
  client/src/pages/child/MoneyPlanPage.jsx
  client/src/pages/context/MoneyPlanContext.js
  client/src/services/NotificationService.js
Labels: fix, feat, styled

#99 [FE] 아이 소비리포트보기 페이지 CSS 수정 완료
  client/src/components/pages/child/payment/PaymentReport.jsx
  client/src/components/pages/child/payment/ReceiveMessage.jsx
  client/src/components/pages/landing/Landing3.jsx
Labels: fix

#100 [FE] 부모 알림아이콘 미사용코드 삭제
  client/src/components/pages/parent/ParentNotificationIcon.jsx
Labels: fix

#101 [FE] 부모 월간리포트 페이지 CSS 수정
  client/src/components/pages/parent/monthly-report/PlanReport.jsx
Labels: fix

#103 [FE] 부모,알림 useSSE 절대경로 설정
  client/src/components/pages/child/ChildNotificationIcon.jsx
  client/src/components/pages/parent/ParentNotificationIcon.jsx
Labels: fix

#104 [FE] 아이 위시페이지 위시상세보기 모달창 css 수정
  client/src/components/pages/child/wish/WishDetailBox.jsx
Labels: fix

#105 [FE] 아이 소비계획세우기, 교육페이지 css 수정
  client/src/components/pages/child/edu/EduVideo.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/components/pages/parent/ParentNotificationIcon.jsx
  server/src/main/java/com/web/spring/service/NotificationService.java
Labels: fix

#106 [FE]plan기능 수정
  client/src/components/pages/child/plan/DoughnutChart.jsx
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/components/pages/parent/monthly-report/PlanReport.jsx
  client/src/pages/child/MoneyPlanPage.jsx
  server/src/main/java/com/web/spring/entity/Parent.java
  server/src/test/java/com/web/spring/test/ChildServiceCommandLineTest.java
Labels: fix

#107 [FE] fix : plan 수정
  client/src/components/pages/child/plan/PlanForm.jsx
Labels: fix

#108 [FE] 아이 위시리스트 페이지 나무 추가
  client/public/images/apple.png
  client/public/images/tree.png
  client/src/components/pages/child/register/FinishWishList.jsx
  client/src/components/pages/child/wish/ActiveWish.jsx
  client/src/data/wishFinishListDummyData.js
  client/src/data/wishSlickDummyData.js
  client/src/data/wishlistDummyData.js
  client/src/pages/child/MyWishListPage.jsx
Labels: fix, feat

#109 [FE] 도니 위시리스트 더미데이터 수정, 소비계획 css 수정
  client/src/components/pages/child/plan/PlanForm.jsx
  client/src/data/wishSlickDummyData.js
  client/src/data/wishlistDummyData.js
Labels: fix
